# Generated by Django 3.0.7 on 2020-08-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polar', '0005_apponitment_book_status_booking_paid_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
