# Generated by Django 3.0.7 on 2020-08-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polar', '0006_auto_20200813_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='decs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
